package netup

import (
	"fmt"
	"net"
	"os"
	"path"
	"strings"
)

// DefaultResolvConfPath is where gosd-init writes DNS servers from a
// lease.
const DefaultResolvConfPath = "/etc/resolv.conf"

// DefaultNetworkUpPath is the marker file gosd-init creates once an
// address is assigned, and removes if the link later goes down.
const DefaultNetworkUpPath = "/run/gosd/network-up"

// WriteResolvConf overwrites path with a `nameserver` line per DNS server
// in dns.
//
// Design choice (the bean asks for one, and to document it): gosd-init's
// rootfs *is* the initramfs itself — the locked 8-step boot sequence never
// pivot_roots or switch_roots to a different filesystem — and Linux's
// initramfs rootfs is already a RAM-backed, fully writable filesystem
// (it's "rootfs", a permanent tmpfs-like mount, not a read-only cpio
// image). That means /etc is writable with no extra work: rather than
// mounting a dedicated tmpfs over /etc (which would also require
// re-populating any other pre-existing /etc contents after the mount hides
// them), this function relies on os.WriteFile's O_CREATE to lazily create
// /etc/resolv.conf on first write if it doesn't already exist as part of
// the initramfs image. If a future board profile ever makes the rootfs
// read-only, this is the function to revisit.
func WriteResolvConf(path string, dns []net.IP) error {
	var b strings.Builder
	b.WriteString("# Generated by gosd-init; do not edit, it will be overwritten on the next lease.\n")
	for _, ip := range dns {
		fmt.Fprintf(&b, "nameserver %s\n", ip)
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

// MarkNetworkUp creates the (empty) marker file at path, and the
// directory it lives in, so anything checking for the file's existence
// (the bean specifies this as the network-up signal) can rely on it once
// an address has been assigned.
func MarkNetworkUp(markerPath string) error {
	if dir := path.Dir(markerPath); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("creating %s: %w", dir, err)
		}
	}
	f, err := os.OpenFile(markerPath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
	if err != nil {
		return fmt.Errorf("creating %s: %w", markerPath, err)
	}
	return f.Close()
}

// ClearNetworkUp removes the marker file at markerPath, if present.
// Removing an already-absent file is not an error: it just means the
// network was never up in the first place.
func ClearNetworkUp(markerPath string) error {
	if err := os.Remove(markerPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("removing %s: %w", markerPath, err)
	}
	return nil
}
