package kernelbuild

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jphastings/gosd/internal/kernelspec"
)

// Filenames written into the work directory bind-mounted read-only at
// /work, and the fixed output filename every build produces alongside the
// board's own artifacts (see writeSourceJSON and Outputs).
const (
	workFragmentName        = "fragment.config"
	workOverlayFragmentName = "overlay-fragment.config"
	workPatchesGoSDDir      = "patches/gosd"
	workPatchesOverlayDir   = "patches/overlay"
	workScriptName          = "build.sh"

	generatedConfigName = "kernel.config"
	sourceJSONName      = "source.json"

	containerSrcDir = "/build/linux"
)

// writeWorkDir populates dir with the generated build script and every
// input file it references: GoSD's config fragment and DTS patches, plus
// the developer overlay's. dir is meant to be bind-mounted read-only at
// /work in the build container.
func writeWorkDir(dir string, spec kernelspec.KernelSpec, overlay Overlay) error {
	if err := os.WriteFile(filepath.Join(dir, workFragmentName), spec.ConfigFragment, 0o644); err != nil {
		return fmt.Errorf("writing GoSD config fragment: %w", err)
	}
	if err := writePatches(dir, workPatchesGoSDDir, spec.DTSPatches); err != nil {
		return fmt.Errorf("writing GoSD DTS patches: %w", err)
	}
	if err := os.WriteFile(filepath.Join(dir, workOverlayFragmentName), overlay.ConfigFragment, 0o644); err != nil {
		return fmt.Errorf("writing developer overlay config fragment: %w", err)
	}
	if err := writePatches(dir, workPatchesOverlayDir, overlay.Patches); err != nil {
		return fmt.Errorf("writing developer overlay DTS patches: %w", err)
	}
	script := buildScript(spec)
	if err := os.WriteFile(filepath.Join(dir, workScriptName), []byte(script), 0o755); err != nil {
		return fmt.Errorf("writing build script: %w", err)
	}
	return nil
}

// writePatches writes each patch under dir/subdir, prefixing a zero-padded
// index so glob order inside the container always matches slice order,
// independent of the patch's own Name.
func writePatches(dir, subdir string, patches []kernelspec.Patch) error {
	full := filepath.Join(dir, subdir)
	if err := os.MkdirAll(full, 0o755); err != nil {
		return err
	}
	for i, p := range patches {
		name := fmt.Sprintf("%03d-%s", i, p.Name)
		if err := os.WriteFile(filepath.Join(full, name), p.Content, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// buildScript generates the bash script run inside container.KernelBuildImage
// to build spec's kernel. It mirrors the steps of the retired
// build/boards/*/build.sh and docker-build.sh scripts (bean gosd-x488):
// clone repo@ref -> apply GoSD DTS patches -> make <defconfig> -> merge the
// GoSD fragment -> apply the developer overlay (patches, then fragment -
// both after GoSD's own) -> make olddefconfig -> assert RequiredY/ForbiddenY
// survived -> build the kernel image + DTB(s) -> copy outputs and the
// generated .config to /out.
func buildScript(spec kernelspec.KernelSpec) string {
	var b strings.Builder

	fmt.Fprint(&b, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&b, "# Generated by internal/kernelbuild for board %q. Do not hand-edit.\n", spec.BoardID)
	fmt.Fprint(&b, "set -euo pipefail\n\n")

	fmt.Fprint(&b, "export DEBIAN_FRONTEND=noninteractive\n")
	fmt.Fprint(&b, "apt-get update -qq\n")
	fmt.Fprint(&b, "apt-get install -y -qq --no-install-recommends \\\n")
	fmt.Fprint(&b, "  ca-certificates git make bc bison flex libssl-dev libelf-dev \\\n")
	fmt.Fprintf(&b, "  python3 rsync cpio kmod patch build-essential %s >/dev/null\n\n", crossPackage(spec.Toolchain))

	fmt.Fprintf(&b, "SRC_DIR=%s\n", containerSrcDir)
	writeCloneSteps(&b, spec.Source)
	fmt.Fprint(&b, "cd \"$SRC_DIR\"\n\n")

	fmt.Fprint(&b, "echo \"==> Applying GoSD device-tree patches\"\n")
	writePatchLoop(&b, "/work/"+workPatchesGoSDDir)

	fmt.Fprintf(&b, "echo \"==> Base config: make %s\"\n", spec.Defconfig)
	fmt.Fprintf(&b, "make %s\n\n", spec.Defconfig)

	fmt.Fprint(&b, "echo \"==> Merging GoSD fragment\"\n")
	fmt.Fprintf(&b, "scripts/kconfig/merge_config.sh -m .config /work/%s\n\n", workFragmentName)

	fmt.Fprint(&b, "echo \"==> Applying developer overlay\"\n")
	writePatchLoop(&b, "/work/"+workPatchesOverlayDir)
	fmt.Fprintf(&b, "if [ -s /work/%s ]; then\n", workOverlayFragmentName)
	fmt.Fprintf(&b, "  scripts/kconfig/merge_config.sh -m .config /work/%s\n", workOverlayFragmentName)
	fmt.Fprint(&b, "fi\n\n")

	fmt.Fprint(&b, "echo \"==> Resolving dependencies: make olddefconfig\"\n")
	fmt.Fprint(&b, "make olddefconfig\n\n")

	writeAssertions(&b, spec)

	fmt.Fprintf(&b, "echo \"==> Building %s\"\n", spec.KernelMakeTarget)
	fmt.Fprintf(&b, "make -j\"$(nproc)\" %s\n\n", spec.KernelMakeTarget)

	// Each distinct DTB make target is built once: additional DTBs usually
	// share the primary's target (pi-3b's "dtbs" builds every blob in one
	// pass), and re-running the same make would only waste time.
	builtDTBTargets := map[string]bool{}
	for _, dtb := range spec.AllDTBs() {
		if builtDTBTargets[dtb.MakeTarget] {
			continue
		}
		builtDTBTargets[dtb.MakeTarget] = true
		fmt.Fprintf(&b, "echo \"==> Building %s\"\n", dtb.MakeTarget)
		fmt.Fprintf(&b, "make -j\"$(nproc)\" %s\n\n", dtb.MakeTarget)
	}

	fmt.Fprint(&b, "echo \"==> Copying outputs to /out\"\n")
	fmt.Fprintf(&b, "install -m 0644 %s /out/%s\n", spec.KernelSourcePath, spec.KernelFilename)
	for _, dtb := range spec.AllDTBs() {
		fmt.Fprintf(&b, "install -m 0644 %s /out/%s\n", dtb.SourcePath, dtb.Filename)
	}
	fmt.Fprintf(&b, "cp .config /out/%s\n\n", generatedConfigName)

	fmt.Fprint(&b, "echo \"==> Done\"\n")
	fmt.Fprint(&b, "ls -la /out\n")

	return b.String()
}

// crossPackage names the Debian cross-toolchain package providing
// spec.Toolchain.CrossCompile, matching the packages the retired build.sh
// scripts install (crossbuild-essential-arm64 / crossbuild-essential-armhf).
func crossPackage(t kernelspec.Toolchain) string {
	switch t.KernelArch {
	case "arm64":
		return "crossbuild-essential-arm64"
	case "arm":
		return "crossbuild-essential-armhf"
	default:
		return "crossbuild-essential-" + t.KernelArch
	}
}

// writeCloneSteps emits the shallow-clone commands for src, mirroring
// build.sh (CommitRef: init/remote/fetch/checkout, matching the Pi boards'
// pinned-commit-on-a-branch handling) or docker-build.sh (TagRef: a plain
// `git clone --depth 1 --branch`, matching the Rockchip-family boards).
func writeCloneSteps(b *strings.Builder, src kernelspec.Source) {
	fmt.Fprintf(b, "echo \"==> Cloning %s at %s (%s)\"\n", src.Repo, src.Ref, src.RefKind)
	switch src.RefKind {
	case kernelspec.TagRef:
		fmt.Fprintf(b, "git clone --quiet --depth 1 --branch %q %q \"$SRC_DIR\"\n", src.Ref, src.Repo)
	default: // kernelspec.CommitRef
		fmt.Fprint(b, "mkdir -p \"$SRC_DIR\"\n")
		fmt.Fprint(b, "git -C \"$SRC_DIR\" init -q\n")
		fmt.Fprintf(b, "git -C \"$SRC_DIR\" remote add origin %q\n", src.Repo)
		fmt.Fprintf(b, "git -C \"$SRC_DIR\" fetch -q --depth 1 origin %q\n", src.Ref)
		fmt.Fprint(b, "git -C \"$SRC_DIR\" checkout -q FETCH_HEAD\n")
	}
}

// writePatchLoop emits a loop applying every *.patch file in dir, in glob
// (i.e. writePatches' zero-padded index) order.
//
// Every patch here targets a freshly cloned, exactly-pinned kernel source
// tree, so a hunk can never legitimately be "already applied", nor need
// fuzzy matching to find its context - if it ever needs either, something
// (most likely a kernel-tag bump shifting nearby .dts lines) has silently
// changed what the patch actually does, and the build must not ship the
// result unnoticed (bean gosd-7acd: a silently-skipped DTS patch means a
// board ships without the peripheral it was meant to enable). --fuzz=0
// refuses any hunk whose context doesn't match verbatim, removing the one
// way `patch` could otherwise apply a hunk at a merely similar-looking,
// wrong location. The explicit grep on patch's own output, on top of
// checking its exit status, is defense in depth against `patch` reporting
// a skipped/reversed/ignored hunk yet an overall success exit code -
// `set -euo pipefail` alone only catches the latter.
func writePatchLoop(b *strings.Builder, dir string) {
	fmt.Fprint(b, "shopt -s nullglob\n")
	fmt.Fprintf(b, "for patch in %s/*.patch; do\n", dir)
	fmt.Fprint(b, "  echo \"    $patch\"\n")
	fmt.Fprint(b, "  patch_out=\"$(patch -p1 --fuzz=0 <\"$patch\" 2>&1)\" || { echo \"$patch_out\" >&2; echo \"FATAL: $patch failed to apply\" >&2; exit 1; }\n")
	fmt.Fprint(b, "  echo \"$patch_out\"\n")
	fmt.Fprint(b, "  if grep -qiE 'revers|ignored|already applied' <<<\"$patch_out\"; then\n")
	fmt.Fprint(b, "    echo \"FATAL: $patch reported a reversed/already-applied/ignored hunk against a freshly cloned pinned source tree - that can never legitimately happen, treating it as a hard failure\" >&2\n")
	fmt.Fprint(b, "    exit 1\n")
	fmt.Fprint(b, "  fi\n")
	fmt.Fprint(b, "done\n\n")
}

// writeAssertions emits the post-olddefconfig gate: every RequiredY symbol
// must have survived as =y, every ForbiddenY symbol must not be =y or =m,
// and (when ModulesDisabled) CONFIG_MODULES must be unset. Every failure is
// echoed to stderr by name before the script exits non-zero, so the names
// reach the caller via the container run's captured stderr tail.
func writeAssertions(b *strings.Builder, spec kernelspec.KernelSpec) {
	fmt.Fprint(b, "echo \"==> Asserting required options survived olddefconfig\"\n")
	fmt.Fprint(b, "missing=0\n")

	if len(spec.RequiredY) > 0 {
		fmt.Fprint(b, "required_y=(\n")
		for _, opt := range normalizeSymbols(spec.RequiredY) {
			fmt.Fprintf(b, "  %s\n", opt)
		}
		fmt.Fprint(b, ")\n")
		fmt.Fprint(b, "for opt in \"${required_y[@]}\"; do\n")
		fmt.Fprint(b, "  if ! grep -qx \"${opt}=y\" .config; then\n")
		fmt.Fprint(b, "    echo \"FATAL: ${opt}=y did not survive olddefconfig\" >&2\n")
		fmt.Fprint(b, "    missing=1\n")
		fmt.Fprint(b, "  fi\n")
		fmt.Fprint(b, "done\n")
	}

	if len(spec.ForbiddenY) > 0 {
		fmt.Fprint(b, "forbidden_y=(\n")
		for _, opt := range normalizeSymbols(spec.ForbiddenY) {
			fmt.Fprintf(b, "  %s\n", opt)
		}
		fmt.Fprint(b, ")\n")
		fmt.Fprint(b, "for opt in \"${forbidden_y[@]}\"; do\n")
		fmt.Fprint(b, "  if grep -qxE \"${opt}=(y|m)\" .config; then\n")
		fmt.Fprint(b, "    echo \"FATAL: ${opt} must not be set but is present\" >&2\n")
		fmt.Fprint(b, "    missing=1\n")
		fmt.Fprint(b, "  fi\n")
		fmt.Fprint(b, "done\n")
	}

	if spec.ModulesDisabled {
		fmt.Fprint(b, "if ! grep -qx \"# CONFIG_MODULES is not set\" .config; then\n")
		fmt.Fprint(b, "  echo \"FATAL: CONFIG_MODULES is set (modules must be disabled)\" >&2\n")
		fmt.Fprint(b, "  missing=1\n")
		fmt.Fprint(b, "fi\n")
	}

	fmt.Fprint(b, "if [ \"${missing}\" -ne 0 ]; then\n")
	fmt.Fprint(b, "  exit 1\n")
	fmt.Fprint(b, "fi\n\n")
}

// normalizeSymbols strips any "=y"/"=m" suffix from each entry, so the
// assertion loops can uniformly append their own suffix regardless of
// whether the KernelSpec stored the bare symbol (the Rockchip-family
// boards' RequiredY/ForbiddenY) or the full "CONFIG_FOO=y" line (the Pi
// boards', derived verbatim from their fragment - see
// kernelspec.requiredYFromFragment).
func normalizeSymbols(opts []string) []string {
	out := make([]string, len(opts))
	for i, opt := range opts {
		opt = strings.TrimSuffix(opt, "=y")
		opt = strings.TrimSuffix(opt, "=m")
		out[i] = opt
	}
	return out
}
