package extbuild

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Filenames written into the work directory bind-mounted read-only at
// /work (see writeWorkDir).
const (
	workScriptName  = "script.sh"
	workWrapperName = "wrapper.sh"
)

// SourceJSONName is the fixed filename every build produces alongside its
// output (see writeSourceJSON), inside its own cache entry directory - it's
// exported so a caller doing its own copy out of Result.CacheDir (e.g.
// cmd/gosd's build-external, which needs to rename this file per external
// to avoid multiple externals colliding on one shared arch output
// directory) has one source of truth for the name, rather than a
// hard-coded string literal of its own.
const SourceJSONName = "source.json"

// writeWorkDir populates dir with the developer's build script, written
// verbatim, and a small generated wrapper that runs it (see wrapperScript).
// dir is meant to be bind-mounted read-only at /work in the build
// container.
func writeWorkDir(dir string, spec Spec) error {
	if err := os.WriteFile(filepath.Join(dir, workScriptName), spec.Script, 0o755); err != nil {
		return fmt.Errorf("writing build script: %w", err)
	}
	wrapper := wrapperScript(spec)
	if err := os.WriteFile(filepath.Join(dir, workWrapperName), []byte(wrapper), 0o755); err != nil {
		return fmt.Errorf("writing wrapper script: %w", err)
	}
	return nil
}

// wrapperScript generates the small entrypoint gosd actually runs inside
// the container (RunSpec.Cmd): it announces the build, runs the
// developer's own script (workScriptName) - which sees the container
// contract's env vars via RunSpec.Env, already set before either script
// runs - and then fails loudly, inside the container and before the
// host-side post-build verification (verifyOutput) even runs, if the
// script didn't actually produce $GOSD_OUTPUT. That turns a broken script
// into an immediate, easy-to-read container-log failure rather than a
// confusing "output missing" surfacing only after the container exits
// successfully.
func wrapperScript(spec Spec) string {
	var b strings.Builder

	fmt.Fprint(&b, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&b, "# Generated by internal/extbuild for external %q. Do not hand-edit.\n", spec.Name)
	fmt.Fprint(&b, "set -euo pipefail\n\n")

	fmt.Fprintf(&b, "echo \"==> Building external %q (GOSD_ARCH=$GOSD_ARCH)\"\n", spec.Name)
	fmt.Fprintf(&b, "bash /work/%s\n\n", workScriptName)

	fmt.Fprint(&b, "if [ ! -f \"$GOSD_OUTPUT\" ]; then\n")
	fmt.Fprint(&b, "  echo \"FATAL: build script did not produce \\$GOSD_OUTPUT ($GOSD_OUTPUT)\" >&2\n")
	fmt.Fprint(&b, "  exit 1\n")
	fmt.Fprint(&b, "fi\n")
	fmt.Fprint(&b, "chmod +x \"$GOSD_OUTPUT\"\n\n")

	fmt.Fprint(&b, "echo \"==> Done\"\n")
	fmt.Fprint(&b, "ls -la /out\n")

	return b.String()
}
